unbind r
bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"

set -g prefix C-Space

unbind %
unbind '"'

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind-key p display-popup -w 80% -h 80% -E serpl

bind-key h select-pane -L 
bind-key j select-pane -D 
bind-key k select-pane -U 
bind-key l select-pane -R 

# Resize panes by 15 cells
bind -r H resize-pane -L 15
bind -r J resize-pane -D 15
bind -r K resize-pane -U 15
bind -r L resize-pane -R 15

set -g base-index 1
set -g renumber-windows on

bind-key P command-prompt -p "project name:" "rename-window '%1'"

set -g @plugin 'TanglingTreats/tmux-everforest'
set -g @tmux-everforest 'dark-medium'

set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'
